### ISSUE TITLE
Mesh

### ISSUE THREAD

**Issue by tetrahydra** [codeniko/shape_predictor_81_face_landmarks#13]
I have a question regarding full_mesh_example.png, how do you produce this?

**Comment by codeniko** [comment]
Sorry for the late response. The points in that image are ones I drew after generating the surrey face model using eos. I wanted to have a visual of all the points in the model and to later draw them with indices so that I can pick out only the points of interest to me. This led to the additional 13 landmarks in my shape predictor outlining the forehead area.

Another visual of this can be found at https://raw.githubusercontent.com/patrikhuber/eos/gh-pages/images/sfm_shape_3448_mesh.png which is the face model itself
