### ISSUE TITLE
How to make training prediction on one's own data set

### ISSUE THREAD

**Issue by zhouhao-learning** [codeniko/shape_predictor_81_face_landmarks#8]
Hello, I have a face data with 194 face key points. I want to use your network to train my data so that I can predict 194 face key points, but there is no explanation in your explanation. Please tell me how should I start?

**Comment by codeniko** [comment]
Hi, the purpose of this project was to share the model that I have trained which enables detecting of 81 facial landmarks on images with faces. Although I have provided a quick summary of how my model came to life, it's not intended to be an in-depth tutorial on how to train your own models. 

Please look into dlib tutorials and documentation for how to train your model since they will be more in-depth than I can ever make it.
